<h2>Conclusiones</h2>
<p>Sobre las conclusiones, no me considero tan experto en la materia como para sacar unas medianamente válidas. El objetivo es plasmar una realidad y luego dejar a los sujetos de este estudio que saquen sus propias conclusiones.</p>
<p>Además, debido a que no existe un censo rolero que nos pueda dar la realidad de la afición en cuestiones de género (tanto de aficionades como de profesionales), solo puedo ofrecer los datos que puedo sacar de las publicaciones hechas. Este estudio sería mucho más real y rico con los datos que pudiera ofrecer ese censo y comparar si la realidad editorial, se acerca a la realidad de la afición.</p>
<p>Sin embargo, gracias a Mirella Machancones y a <a href="https://lamirada.produccionesgorgona.com/rol-y-genero/" target="_blank">su estudio de 2022 sobre «ROL Y GÉNERO»</a>, podemos tratar interpretar los datos de publicación de juegos de rol.</p>

<blockquote style="font-style: italic; padding: 10px; border: 1px solid var(--main-color);">«La encuesta se elaboró en verano de 2022 y tuvo un total de 524 respuestas, lo que lo convierte en un muestreo bastante extensivo de lo que es nuestra afición. Se realizó siguiendo el método de la bola de nieve, compartida por redes sociales y grupos de rol conocidos. Pese a ello, creo que los resultados que nos arroja resultan bastante significativos.<br/><br/>Como suelo hacer en los últimos posts, voy a usar el femenino genérico para este artículo, así que no asustéis cuando empiece a usar «encuestadas». Al fin y al cabo, todas somos personas.[...]<br/><br/>
Del total de las encuestadas, un 57,3% eran hombres, un 33,6% mujeres y un 6,7% personas no binarias (fig.1). El resto de las encuestadas no quisieron responder a la pregunta o consideran tener un género no recogido por la encuesta. En cualquier caso, a la hora de analizar los datos de manera cruzada, tendremos en cuenta como colectivos a hombres, mujeres y personas no binarias. He de señalar antes de comenzar el análisis, que no se ha tenido en cuenta a la población transmasculina y transfemenina como colectivos separados, lo que visto con perspectiva puede sesgar algo los casos (algunas personas transmasculinas han señalado en los comentarios que sufrieron una experiencia diferente cuando eran percibidas como mujeres).»<br/><br/>
<img src="https://lamirada.produccionesgorgona.com/wp-content/uploads/2023/01/image.png" style="margin: auto; display: block; max-width: 100%;" alt="Gráfico de la encuesta de Machancones sobre rol y género"/></blockquote>

<p>XXX</p>

<blockquote style="font-style: italic; padding: 10px; border: 1px solid var(--main-color);">«Aunque partimos de una situación de ventaja porcentual para las mujeres entre las menores de 25 años, esto se invierte en el grupo de los 26 a los 35, aunque mantiene unos porcentajes más cercanos a la igualdad (fig. 4). Sin embargo, en los dos siguientes grupos de edad el desequilibrio se acentúa bastante, hasta el punto de alejar bastante de la igualdad el resultado final representado.»<br/><br/>
<img src="https://lamirada.produccionesgorgona.com/wp-content/uploads/2023/01/image-3.png" style="margin: auto; display: block; max-width: 100%;" alt="Gráfico de la encuesta de Machancones sobre la distribución de género y edad en las jugadoras de rol."/></blockquote>
<p>XXX</p>
<h3>Fallos de estas conclusiones</h3>
<p>Estas conclusiones se basan en un estudio realizado en 2022 que tiene algunas limitaciones que hay que tener en cuenta al usarlo. Principalmente, la muestra no puede ser considerada representativa del coletivo rolero, no tiene por qué estar equivocada y seguramente no lo esté o se haya quedado muy cerca de las cifras reales, pero los métodos usados para obtener los datos no podemos considerarlos los más adecuados. Aun así, no deja de tener su valor y, si bien no exacto, nos da una idea muy aproximada de la realidad.</p>
<p>Se ha considerado que los porcentajes de autores, autoras y autores NB a los que se publica material rolero deberían ser similares a los porcentajes de jugadoras, jugadores NB y jugadores y esto podría no ser correcto.</p>
<p>Se debería que haber comparado los datos de autores, autoras y autores NB frente al colectivo en general de aficionados españoles con los mismos datos de países culturalmente afines y que pudieran tener una industria rolera parecida, como podrían ser Italia o Francia. De esa forma se podŕia haber precisado mejor si la correlación entre porcentajes de género entre personas autoras y personas jugadoras se mantienen o tienen algún tipo de desviación.</p> 
<p>Por ahora solo estamos trabajando en el año 2026 y no sabemos si los datos son una cosa excepcional y cambian radicalmente en otros años, si se mantienen en los sucesivos años o si hay una tendencia de subida o de bajada. Por suerte, este problema se va a solucionar, ya que la idea del proyecto es recoger datos todos los años. De esta forma podremos estudiar la evolución de estos datos.</p>