<p>Este estudio trata de mostrar el papel de las autoras y autores no binaries de material rolero en España anualmente, empezando por el 2026.</p>
<p>A la hora de elaborar este estudio se han seguido las siguientes reglas y parámetros:</p>
<ol>
<li>Se han registrado los productos roleros (juegos, aventuras, suplementos, ensayos teóricos, manuales de técnicas roleras, etc.) escritos por autores españoles y publicados por editoriales y grupos creativos. No importa el idioma en que se escriba, castellano, catalán, euskera, galego, inglés, etc. Las traducciones a otros idiomas de juegos publicados en año anteriores cuentan como títulos publicados en el año en cuestión.</li>
<li>Para el estudio buscamos que haya una intención de publicar el título en sí mismo, no como un producto añadido a otro con carácter gratuito y/o promocional. Es por ello que solo se registran <b>productos publicados físicamente de 16 o más páginas y con PVP</b>. Se busca excluir material de promoción que, por ejemplo, ofrezcan gratis las editoriales en determinadas ocasiones o recompensas especiales de campañas de mecenazgo.</li>
<li>Se han <b>excluido títulos autopublicados</b> porque el estudio busca reflejar cómo se relacionan editoriales/grupos creativos con autores, relación que en los autopublicados no se da.</li>
<li>Se considera <b>autore a aquella persona que la editorial/grupo creativo ha promocionado como autore de la publicación</b>. En caso de no quedar claro, se ha considerado autore o autores a le escritore o escritores principales y se han excluido a personas que solo han trabajado en su edición, maquetación, corrección, ilustración y/o promoción.</li>
<li>Se usa <b>el número de páginas impresas para estimar la envergadura o complejidad de las obras que llegan a publicarse</b>. No es un sistema perfecto, pero es mucho más realista que simplemente contabilizar el número de obras publicadas. Cuando unas obras tiene varias personas autoras se ha dividido el número de páginas entre el número de autores a la hora de contabilizar cuántas páginas ha escrito cada autore.</li>
<li>Se ha usado el género atribuido a cada nombre propio para determinar si estamos ante una autora o un autor. No es el sistema ideal, pero a falta de pronombres (y su uso en el material promocional) es lo más lejos que se ha podido llegar sin tener que preguntar directamente a les autores e inmiscuirse en la privacidad de las personas. En la medida que se ha podido se han buscado las redes sociales de les autores para tratar determinar si son no binaries mediante sus pronombres.</li>
</ol>
<p>El estudio es algo vivo que se actualiza según pasan los meses hasta poder tener una idea general del año al terminar este. Si bien, hasta finalizado el año no se tendrán datos definitivos y totales, sí permiten ver tendencias.</p> 
<p>El estudio puede tener títulos que han sido anunciados y también que se supone que publicarán en el año. En caso de que luego no se cumpla la fecha, de forma que si al acabar el año o la editorial anunciar otra fecha, serán movidos a otro año. Estos cambios son automáticos y quedan registrados de forma que junto a cada estudio vendrá la fecha de la última actualización del proyecto.</p>
<p style="border: 1px solid var(--main-color); padding: 5px;">Si detectas datos desactualizados o crees que falta algún título publicado, puedes ponerte en contacto conmigo a través de <a href="mailto:monclus.jorge+autoras@gmail.com">monclus.jorge@gmail.com</a>.</p>